version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run: docker build -t climbing-sites:0 .