version: 2.1
jobs:
  build:
    docker:
     - image: circleci/node:lts

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: build docker image
          working_directory: ./src
          command: docker build -t climbing-sites:0 -f PinkPoint.ClimbingRoutes/Dockerfile .