version: 2.1
jobs:
  git-version:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.1

    steps:
      - run:
          name: install git version pre-requisites
          command: |
            apt-get update
            apt-get install -y --no-install-recommends \
              libc6 \
              zlib1g-dev \
              libcomerr2 \
              libc6-dev \
              libgcrypt20 \
              libkeyutils1 \
              libcurl3-gnutls \
              libsasl2-2 \
              libgpg-error0 \
              libcurl3

      - checkout

      - jq/install

      - run:
          name: install git version
          command: |
            dotnet tool install --global GitVersion.Tool --version 5.0.1
            echo "export PATH=$PATH:~/.dotnet/tools" >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: git version
          command: |
            dotnet-gitversion /nocache /output json >> git-version.json
            cat git-version.json
            for s in $(cat git-version.json | jq -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]" ); do
              echo "export $s" >> $BASH_ENV
            done
            source $BASH_ENV
            echo "$InformationalVersion"

      - persist_to_workspace:
          root: /root/project
          paths:
            - ./

  build_climbing_routes:
    docker:
      - image: circleci/node:lts

    steps:
      - attach_workspace:
          at: /home/circleci/project

      - setup_remote_docker

      - run:
          name: restore git version
          command: |
            cat git-version.json
            cat 
            for s in $(cat git-version.json | jq -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]" ); do
              echo "$s"
              echo "export $s" >> $BASH_ENV
            done
            source $BASH_ENV
            printenv

      - run:
          name: build docker image
          working_directory: ./src
          command: |
           docker build -t docker.pkg.github.com/lehmamic/pinkpoint/climbing-routes:${FullSemVer} -f PinkPoint.ClimbingRoutes/Dockerfile .

      - run:
          name: docker login
          command: docker login docker.pkg.github.com -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: docker push
          command: docker push docker.pkg.github.com/lehmamic/pinkpoint/climbing-routes:${FullSemVer}

  package_climbing_routes:
    docker:
      - image: circleci/node:lts

    steps:
      - attach_workspace:
          at: /home/circleci/project

      - run:
          name: restore git version
          command: |
            cat git-version.json
            cat 
            for s in $(cat git-version.json | jq -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]" ); do
              echo "$s"
              echo "export $s" >> $BASH_ENV
            done
            source $BASH_ENV
            printenv

      - run:
          name: create helm chart
          command: |
            sed 's/#{app-version}/0.1-test/g' ./PinkPoint.ClimbingRoutes/Chart.yaml.template > ./PinkPoint.ClimbingRoutes/Chart.yaml
            cat ./PinkPoint.ClimbingRoutes/Chart.yaml
            sed 's/#{app-version}/0.1-test/g' ./PinkPoint.ClimbingRoutes/values.yaml.template > ./PinkPoint.ClimbingRoutes/values.yaml
            cat ./PinkPoint.ClimbingRoutes/values.yaml
          working_directory: ./helm_charts
  build_api_gateway:
    docker:
      - image: circleci/node:lts

    steps:
      - attach_workspace:
          at: /home/circleci/project

      - setup_remote_docker

      - run:
          name: restore git version
          command: |
            cat git-version.json
            cat 
            for s in $(cat git-version.json | jq -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]" ); do
              echo "$s"
              echo "export $s" >> $BASH_ENV
            done
            source $BASH_ENV
            printenv

      - run:
          name: build docker image
          working_directory: ./src
          command: |
           docker build -t docker.pkg.github.com/lehmamic/pinkpoint/api-gateway:${FullSemVer} -f PinkPoint.ApiGateway/Dockerfile .

      - run:
          name: docker login
          command: docker login docker.pkg.github.com -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: docker push
          command: docker push docker.pkg.github.com/lehmamic/pinkpoint/api-gateway:${FullSemVer}

orbs:
  jq: circleci/jq@1.9.0

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - git-version

      - build_climbing_routes:
          requires:
            - git-version

      - package_climbing_routes:
          requires:
            - build_climbing_routes

      - build_api_gateway:
          requires:
            - git-version