version: 2.1
jobs:
  git-version:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.1

    steps:
      - run:
          name: install git version pre-requisites
          command: |
            apt-get update
            apt-get install -y --no-install-recommends \
              libc6 \
              zlib1g-dev \
              libcomerr2 \
              libc6-dev \
              libgcrypt20 \
              libkeyutils1 \
              libcurl3-gnutls \
              libsasl2-2 \
              libgpg-error0 \
              libcurl3

      - checkout

      - jq/install

      - run:
          name: install git version
          command: |
            dotnet tool install --global GitVersion.Tool --version 5.0.1
            echo "export PATH=$PATH:~/.dotnet/tools" >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: git version
          command: |
            for s in $(dotnet-gitversion /nocache /output json | jq -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]" ); do
              echo "export $s" >> $BASH_ENV
            done
            source $BASH_ENV
            echo "$InformationalVersion"

      - persist_to_workspace:
          root: workspace
          paths:
            - .

  build:
    docker:
      - image: circleci/node:lts

    steps:
      - attach_workspace

      - setup_remote_docker

      - run:
          name: build docker image
          working_directory: ./src
          command: |
           docker build -t docker.pkg.github.com/lehmamic/pinkpoint/climbing-sites:${FullSemVer} -f PinkPoint.ClimbingRoutes/Dockerfile .

      - run:
          name: docker login
          command: docker login docker.pkg.github.com -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: docker push
          command: docker push docker.pkg.github.com/lehmamic/pinkpoint/climbing-sites:${FullSemVer}

orbs:
  jq: circleci/jq@1.9.0

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - git-version

      - build:
          requires:
            - git-version