version: 2.1
jobs:
  git-version:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.1

    steps:
      - run:
          name: install git version pre-requisites
          command: |
            apt-get update
            apt-get install -y --no-install-recommends \
              libc6 \
              zlib1g-dev \
              libcomerr2 \
              libc6-dev \
              libgcrypt20 \
              libkeyutils1 \
              libcurl3-gnutls \
              libsasl2-2 \
              libgpg-error0 \
              libcurl3

      - checkout

      - run:
          name: install git version
          command: dotnet tool install --global GitVersion.Tool --version 5.0.1

      - run:
          name: git version
          command: ~/.dotnet/tools/dotnet-gitversion /output buildserver
  build:
    docker:
      - image: circleci/node:lts

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: build docker image
          working_directory: ./src
          command: |
           docker build -t docker.pkg.github.com/lehmamic/pinkpoint/climbing-sites:unversioned -f PinkPoint.ClimbingRoutes/Dockerfile .

      - run:
          name: docker login
          command: docker login docker.pkg.github.com -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: docker push
          command: docker push docker.pkg.github.com/lehmamic/pinkpoint/climbing-sites:unversioned

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - git-version

      - build:
          requires:
            - git-version