version: 2.1
jobs:
  build:
    docker:
     - image: circleci/node:lts

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: build docker image
          working_directory: ./src
          command: docker build -t docker.pkg.github.com/lehmamic/pinkpoint/climbing-sites:unversioned -f PinkPoint.ClimbingRoutes/Dockerfile .

      - run:
          name: docker login
          command: docker login docker.pkg.github.com -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: docker push
          command: docker.pkg.github.com/lehmamic/pinkpoint/climbing-sites:unversioned