apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pinkpoint-apigateway
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: pinkpoint-api.c90b5ad23c6d4683a634.westeurope.aksapp.io
    http:
      paths:
      - backend:
          serviceName: pinkpoint-apigateway
          servicePort: 80
        path: /