apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ravendb
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: raven-db.c90b5ad23c6d4683a634.westeurope.aksapp.io
    http:
      paths:
      - backend:
          serviceName: ravendb
          servicePort: 8080
        path: /
  - host: tcp.raven-db.c90b5ad23c6d4683a634.westeurope.aksapp.io
    http:
      paths:
      - backend:
          serviceName: ravendb
          servicePort: 38888
        path: /