apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ravendb
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
  - host: raven-db.c90b5ad23c6d4683a634.westeurope.aksapp.io
    http:
      paths:
      - backend:
          serviceName: ravendb
          servicePort: 443
        path: /
  - host: tcp.raven-db.c90b5ad23c6d4683a634.westeurope.aksapp.io
    http:
      paths:
      - backend:
          serviceName: ravendb
          servicePort: 38888
        path: /