apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pinkpoint-climbingroutes
  labels:
    app: pinkpoint-climbingroutes
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pinkpoint-climbingroutes
  template:
    metadata:
      labels:
        app: pinkpoint-climbingroutes
    spec:
      containers:
      - name: climbingroutes
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: RavenSettings__Urls__0
          value: http://ravendb:8080
        - name: RavenSettings__DatabaseName
          value: PinkPoint.ClimbingRoutes
      imagePullSecrets:
      - name: {{ .Values.image.imagePullSecret }}