version: '3.4'

services:

  pinkpoint.climbingroutes:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5001:80"

  pinkpoint.apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - http://+:80
    ports:
      - "5000:80"
    volumes:
      - ./ocelot.config.json:/app/ocelot.config.json

  ravendb:
    ports:
    - target: 443
      published: 443
      mode: host
    - target: 8080
      published: 8080
      mode: host
    - target: 38888
      published: 38888
      mode: host
    volumes:
    - db-data:/opt/RavenDB/Server/RavenData

volumes:
  db-data:
