version: '3.4'

services:

  pinkpoint.climbingroutes:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5001:80"

  pinkpoint.apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - http://+:80
    ports:
      - "5000:80"
    volumes:
      - ./ocelot.config.json:/app/ocelot.config.json

  ravendb:
    ports:
    - target: 443
      published: 443
      mode: host
    - target: 8080
      published: 8080
      mode: host
    - target: 38888
      published: 38888
      mode: host
    volumes:
    - db-data:/opt/RavenDB/Server/RavenData

  pinkpoint.identityprovider:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44301
    ports:
      - "33937:80"
      - "44301:443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
  pinkpoint.imagerecognition:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44325
    ports:
      - "46640:80"
      - "44325:443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
volumes:
  db-data:


