version: '3.4'

services:
  ravendb:
    image: ravendb/ravendb:ubuntu-latest
    environment:
    - RAVEN_ARGS='--Setup.Mode=None'
    - RAVEN_Security_UnsecuredAccessAllowed='PrivateNetwork'
    ports:
    - target: 443
      published: 443
      mode: host
    - target: 8080
      published: 8080
      mode: host
    - target: 38888
      published: 38888
      mode: host
    volumes:
    - db-data:/opt/RavenDB/Server/RavenData
volumes:
  db-data:
