version: '3.4'

services:

  pinkpoint.climbingroutes:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5001:80"

  pinkpoint.apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - http://+:80
    ports:
      - "5000:80"
    volumes:
      - ./ocelot.config.json:/app/ocelot.config.json

  pinkpoint.identityprovider:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5100:80"
 
  pinkpoint.imagerecognition:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5002:80"

  pinkpoint.cockpit:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5200:80"

  pinkpoint.routesearch:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5003:80"

  pinkpoint.media:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5004:80"

  ravendb:
    environment:
    - RAVEN_ARGS='--Setup.Mode=None'
    - RAVEN_Security_UnsecuredAccessAllowed='PrivateNetwork'

    ports:
    - target: 443
      published: 443
      mode: host
    - target: 8080
      published: 8080
      mode: host
    - target: 38888
      published: 38888
      mode: host
    volumes:
    - db-data:/opt/RavenDB/Server/RavenData
    
volumes:
  db-data:

